plugins {
    id 'java-library'
}

group = 'com.luokuiai'
version = findProperty('releaseVersion') ?: '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    api platform(libs.org.springframework.boot.spring.boot.dependencies.x2)
    api project(':flovira-mybatis-plus-sb3-starter')
    api project(':flovira-plugin-json-jackson')
    api project(':flovira-plugin-ui-sb-web')
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-jdbc'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

description = 'Shared backend for the composable Flovira examples'
